; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26131.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\kuma\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
